services:
  sensors_api:
    build:
      context: .
      dockerfile: src/Services/Sensors/Sensors.API/Dockerfile

  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always

  postgres_sensors:
    image: postgres
    restart: always
    container_name: postgres_sensors